### ISSUE TITLE
INIReader 在 Linux 下编译报错

### ISSUE THREAD

**Issue by zchrissirhcz** [scarsty/mlcc#9]
![图片](https://github.com/scarsty/mlcc/assets/3831847/fd4f1148-1c33-454c-b81c-c0abb06873d1)

最简测试代码：
```cpp
#include "INIReader.h"

int main()
{
    return 0;
}
```

mlcc 版本： 当前（2023-09-16 11:52:45）最新
> * c98829f 2023-09-15 | no message (HEAD -> master, origin/master, origin/HEAD) [GPU02\sty]

**Comment by zchrissirhcz** [comment]
环境: G++ 11.4, ubuntu 22.04

![图片](https://github.com/scarsty/mlcc/assets/3831847/b5894f80-0797-4b8b-bab0-dbb84822955f)

**Comment by scarsty** [comment]
已修改
